# Generated by Django 2.0.2 on 2018-02-16 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payload',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payload',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
